name: rbzNightVision
author: therbz
version: 1.6.2
description: Allows users to toggle nightvision on/off
api-version: 1.17
main: me.therbz.rbznightvision.NightVision
commands:
  nightvision:
    description: Toggle night vision on or off for you or a specified player, or reload the plugin
    usage: /nightvision [<Player> | reload]
    aliases: [nv, nvision, nightv]
permissions:
  rbznv.use:
    description: Allows use of /nv on self
    default: op
  rbznv.use.others:
    description: Allows use of /nv on other players
    default: op
  rbznv.reload:
    description: Allows use of /nv reload to reload the plugin
    default: op
  rbznv.cooldown.bypass:
    description: Bypass the command cooldown
    default: op
  rbznv.onjoin:
    description: Enable night vision when joining
    default: false