#########################################
#                                       #
#    rbzNightVision v1.6.1 by therbz    #
#                                       #
#########################################

# The number of ticks the nightvision effect will last
# Maximum value: 2147483647 = 3 and a half years
# 1 second = 20 ticks
# 1 day = 1728000 ticks
nvticks: 1728000

# Cooldown (in seconds) between using /nv
# This can be bypassed using rbznv.cooldown.bypass
# Set to 0 to disable
cooldown: 0

# Messages
messages:
  reload: "&6&lNV &8\u00BB &aSuccessfully reloaded &frbzNightVision"
  nvenable: "&6&lNV &8\u00BB &aToggled nightvision &fon"
  nvdisable: "&6&lNV &8\u00BB &cToggled nightvision &foff"
  no-permission: "&c&lNV &8\u00BB &4You do not have permission to execute this command!"
  incorrect-usage: "&c&lNV &8\u00BB &4Incorrect arguments! Correct usage: &c%usage%"
  not-player: "&cYou must be a player to execute this command!"
  cooldown: "&c&lNV &8\u00BB &4You cannot use this command for &c%seconds% &4seconds!"

  # Messages related to /nv <other player>
  # Placeholder %target% can be used for nvenable-sender and nvdisable-sender
  other-player:
    unknown-target: "&c&lNV &8\u00BB &4Could not find that player!"
    no-permission: "&c&lNV &8\u00BB &4You do not have permission to use this on other players!"
    nvenable-sender: "&6&lNV &8\u00BB &aToggled nightvision &fon &afor &f%target%"
    nvdisable-sender: "&6&lNV &8\u00BB &cToggled nightvision &foff &cfor &f%target%"

# DO NOT TOUCH
config-version: 3